### ISSUE TITLE
Add an English translation

### ISSUE THREAD

**Issue by HeyAnirudh** [AndreAlbu/Questoes-beecrowd-Python#36]
Hello just saw this repo, was curious about what it does, but the language isn't known to me, so with all due respect could you translate it into English?

**Comment by AndreAlbu** [comment]
Yes I can, I will add a brief description in the read me. I will suggest that the new contributions also be in another language.

**Comment by HeyAnirudh** [comment]
> Yes I can, I will add a brief description in the read me. I will suggest that the new contributions also be in another language.

That's great! Thank you
